name: Build Artifacts
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EVENT: my_event
        ORG: manojp748
        REPO: repoA
      run: |
        echo "try 1"
        curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
        echo "try 2"
        curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token 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" --request POST --data '{"event_type": "my_event"}' https://api.github.com/repos/manojp748/repoA/dispatches
