name: workflow_02
on:
  workflow_dispatch:
     inputs:
      workflow_02:
        description: 'Ù‹Workflow 1 which will be triggered'
        required: true
        default: 'workflow_01'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':manojp748'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':repoA' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          run: |
          curl -d "{\"event_type\": \"my_event\"}" -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/manojp748/repoA/dispatches"
          curl -d "{\"event_type\": \"my_event\"}" -H "Content-Type: application/json" -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/manojp748/repoA/workflows/workflow_01/dispatches"
          curl -X POST https://api.github.com/repos/manojp748/repoA/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
      - uses: actions/checkout@v3
